[package]
name = "shad3"
version = "1"
edition = "2021"
authors = ["Alex Goven"]
description = "App for hashing entries in blocklists"
license = "GNU GPL v3"
repository = "https://github.com/styromaniac/shad3"

[dependencies]
anyhow = "1.0.75"
rayon = "1.7.0"
reqwest = { version = "0.11.20", features = ["stream"] }
sha3 = "0.10.8"
tokio = { version = "1.32.0", features = ["full"] }
regex = "1.9.3"
futures = "0.3.28"
indicatif = "0.17.6"
hex = "0.4.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
