---
name: Rust CI and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: aarch64
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            arch: x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
          - os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            arch: aarch64
            target: aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: >-
            ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64' }}
          command: build
          args: >-
            --release
            --target ${{ matrix.target }}
            --bin shad3
      - name: Prepare artifacts
        shell: pwsh
        run: |
          New-Item -Path artifacts -ItemType Directory -Force
          $TARGET_DIR = "target/${{ matrix.target }}/release"
          $OS = if ("${{ matrix.os }}" -eq "ubuntu-latest") { "linux" } `
                elseif ("${{ matrix.os }}" -eq "macos-latest") { "macos" } `
                else { "windows" }
          if ($OS -eq "windows") {
            $EXE_FILE = "shad3.exe"
            $ARTIFACT_NAME = "shad3.exe"
            $ARCHIVE_NAME = "shad3-${OS}_${{ matrix.arch }}.zip"
            Copy-Item "$TARGET_DIR\$EXE_FILE" "artifacts\$ARTIFACT_NAME"
            Compress-Archive -Path "artifacts\$ARTIFACT_NAME" `
              -DestinationPath "artifacts\$ARCHIVE_NAME"
          } else {
            $BIN_FILE = "shad3"
            $ARTIFACT_NAME = "shad3"
            $ARCHIVE_NAME = "shad3-${OS}_${{ matrix.arch }}.tar.gz"
            Copy-Item "$TARGET_DIR/$BIN_FILE" "artifacts/$ARTIFACT_NAME"
            tar -czf "artifacts/$ARCHIVE_NAME" -C artifacts $ARTIFACT_NAME
          }
      - uses: actions/upload-artifact@v4
        with:
          name: shad3-${{ matrix.os }}_${{ matrix.arch }}
          path: artifacts/*

  publish:
    name: Publish
    if: github.ref == 'refs/heads/main'
    needs: [check, test, fmt, clippy, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Check version changes
        id: check_version
        run: |
          git fetch origin main
          CURRENT_VERSION=$(grep '^version = ' Cargo.toml | \
            sed -E 's/version = "(.*)"/\1/')
          MAIN_VERSION=$(git show origin/main:Cargo.toml | \
            grep '^version = ' | sed -E 's/version = "(.*)"/\1/')
          echo "current=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
          echo "main=${MAIN_VERSION}" >> $GITHUB_OUTPUT
          if [ "$CURRENT_VERSION" != "$MAIN_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Create and push tag
        if: steps.check_version.outputs.changed == 'true'
        run: |
          VERSION="${{ steps.check_version.outputs.current }}"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
      - name: Publish to crates.io
        if: steps.check_version.outputs.changed == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
      - name: Verify published version
        if: steps.check_version.outputs.changed == 'true'
        run: |
          sleep 15
          VERSION="${{ steps.check_version.outputs.current }}"
          SEARCH_RESULT=$(cargo search shad3 --limit 1)
          PUBLISHED_VERSION=$(echo "$SEARCH_RESULT" | \
            sed -nE 's/^[^"]*"//; s/".*//p')
          if [[ "$PUBLISHED_VERSION" != "${VERSION}" ]]; then
            echo "Version mismatch" && exit 1
          fi
      - name: Download artifacts
        if: steps.check_version.outputs.changed == 'true'
        uses: actions/download-artifact@v4
        with:
          pattern: shad3-*
          path: artifacts
          merge-multiple: true
      - name: Create GitHub Release
        if: steps.check_version.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.check_version.outputs.current }}"
          gh release create "v${VERSION}" \
            --title "Release v${VERSION}" \
            --notes "Release v${VERSION}" \
            artifacts/*.tar.gz artifacts/*.zip
