name: Rust CI for Android (aarch64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android

    - name: Install cross
      run: cargo install cross

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Clippy
      run: cross clippy --target aarch64-linux-android -- -D warnings

    - name: Build
      run: cross build --target aarch64-linux-android --release

    - name: Run tests
      run: cross test --target aarch64-linux-android --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-linux-android-build
        path: target/aarch64-linux-android/release/shad3
