---
name: Rust CI and Publish

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            target: unknown-linux-gnu
          - os: macos-latest
            target: apple-darwin
          - os: windows-latest
            target: pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: >-
            ${{ matrix.os == 'ubuntu-latest' &&
            matrix.arch == 'aarch64' }}
          command: build
          args: >-
            --release
            --target ${{ matrix.arch }}-${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: >-
            target/${{ matrix.arch }}-${{ matrix.target }}/release/shad3*

  publish:
    name: Publish
    needs: [check, test, fmt, clippy, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-edit
      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Check if should publish
        id: should_publish
        run: |
          if [[ "${{ github.event_name }}" == 'push' && \
          "${{ startsWith(github.ref, 'refs/tags/') }}" == 'true' ]]
          then
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT
          fi
      - name: Get version from tag
        if: steps.should_publish.outputs.publish == 'true'
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" \
          >> $GITHUB_OUTPUT
      - name: Update version in Cargo.toml
        if: steps.should_publish.outputs.publish == 'true'
        run: |
          cargo set-version \
          ${{ steps.get_version.outputs.VERSION }}
      - name: Commit updated Cargo.toml
        if: steps.should_publish.outputs.publish == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Cargo.toml
          git commit -m "Update version to \
          ${{ steps.get_version.outputs.VERSION }}"
          git push origin HEAD:${{ github.ref }}
      - name: Publish to crates.io
        if: steps.should_publish.outputs.publish == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
      - name: Verify published version
        if: steps.should_publish.outputs.publish == 'true'
        run: |
          sleep 15
          PUBLISHED_VERSION=$(cargo search shad3 --limit 1 | \
          sed -nE 's/^[^"]*"//; s/".*//p')
          if [ "$PUBLISHED_VERSION" != \
          "${{ steps.get_version.outputs.VERSION }}" ]
          then
            echo "Version mismatch" && exit 1
          fi
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: sudo apt-get install -y gh
      - name: Create GitHub Release
        if: steps.should_publish.outputs.publish == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "v${{ steps.get_version.outputs.VERSION }}" \
          --title "Release ${{ steps.get_version.outputs.VERSION }}" \
          --notes "Release notes for version \
          ${{ steps.get_version.outputs.VERSION }}" \
          ./artifacts/*/* \
          --repo ${{ github.repository }}
