---
name: Rust CI and Publish

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            target: unknown-linux-gnu
          - os: macos-latest
            target: apple-darwin
          - os: windows-latest
            target: pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: >-
            ${{ matrix.os == 'ubuntu-latest' &&
            matrix.arch == 'aarch64' }}
          command: build
          args: >-
            --release
            --target ${{ matrix.arch }}-${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: >-
            target/${{ matrix.arch }}-${{ matrix.target }}/release/shad3*

  publish:
    name: Publish
    needs: [check, test, fmt, clippy, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-edit
      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | \
          sed 's/version = "\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Create and push tag
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag "v${{ steps.get_version.outputs.VERSION }}"
          git push origin "v${{ steps.get_version.outputs.VERSION }}"
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
      - name: Verify published version
        run: |
          sleep 15
          PUBLISHED_VERSION=$(cargo search shad3 --limit 1 | \
          sed -nE 's/^[^"]*"//; s/".*//p')
          if [ "$PUBLISHED_VERSION" != \
          "${{ steps.get_version.outputs.VERSION }}" ]
          then
            echo "Version mismatch" && exit 1
          fi
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: sudo apt-get install -y gh
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for artifact in ./artifacts/*/*; do
            filename=$(basename "$artifact")
            dir=$(basename $(dirname "$artifact"))
            gh release create "v${{ steps.get_version.outputs.VERSION }}" \
              --title "Release ${{ steps.get_version.outputs.VERSION }}" \
              --notes "Release ${{ steps.get_version.outputs.VERSION }}" \
              "$artifact#$dir-$filename" \
              --repo ${{ github.repository }}
          done
