name: Rust CI for Android (aarch64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NDK_VERSION: "23.2.8568313"
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '9477386'

    - name: Install Android NDK
      run: |
        sdkmanager --install "ndk;${{ env.NDK_VERSION }}"
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cross
      run: cargo install cross

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Clippy
      run: cross clippy --target aarch64-linux-android -- -D warnings

    - name: Build
      env:
        RUSTFLAGS: "-C link-arg=-nostdlib++"
      run: cross build --verbose --release --target aarch64-linux-android

    - name: Run tests
      env:
        RUSTFLAGS: "-C link-arg=-nostdlib++"
      run: cross test --verbose --target aarch64-linux-android

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-linux-android-build
        path: target/aarch64-linux-android/release/shad3

    - name: Upload debug symbols
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-linux-android-debug-symbols
        path: target/aarch64-linux-android/release/shad3.d
