name: Rust CI for Android (aarch64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        override: true
        components: rustfmt, clippy

    - name: Install cross
      run: cargo install cross

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: clippy
        args: --target aarch64-linux-android -- -D warnings

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --release --target aarch64-linux-android

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --verbose --target aarch64-linux-android

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aarch64-linux-android-build
        path: target/aarch64-linux-android/release/
